type ScenarioModule = "daily" | "management" | "leadership";
type ScenarioTemplate = { slug: string; title: string; context: string; focus: string; task: string; transfer: string };
type ScenarioLevel = { level: number; label: string; prompt: string; transfer: string };

const functions = ["Human Resources", "Engineering", "Product Management", "Finance", "Sales", "Marketing", "Operations", "Procurement", "Customer Success", "General Management", "Entrepreneurship", "Other/custom"];
const goals = ["Start conversations", "Explain ideas clearly", "Give constructive feedback", "Present recommendations", "Handle challenging questions"] as const;
const levels: ScenarioLevel[] = [
  { level: 1, label: "Clarity foundation", prompt: "State the situation, your main point, and one useful next step", transfer: "Change the setting while keeping the same clear structure" },
  { level: 2, label: "Structured message", prompt: "Organize the context, key message, supporting detail, and action", transfer: "Adapt the same message for a different colleague" },
  { level: 3, label: "Evidence and trade-offs", prompt: "Use evidence, explain the implication, and make a reasoned recommendation", transfer: "Respond when one important assumption changes" },
  { level: 4, label: "Audience adaptation", prompt: "Anticipate a concern, adapt your language to the audience, and protect the relationship", transfer: "Answer a challenging follow-up from another stakeholder" },
    { level: 5, label: "Leadership transfer", prompt: "Lead through ambiguity, name the decision, and create alignment without inventing certainty", transfer: "Transfer the communication approach to a new high-stakes situation" },
];

const templates: Record<ScenarioModule, ScenarioTemplate[]> = {
  daily: [
    { slug: "new-colleague", title: "Meet a new colleague", context: "You have thirty seconds before a project meeting with a colleague you have not met.", focus: "Conversation initiation", task: "Open with a warm introduction, connect your role to the project, and ask one question that helps you work together.", transfer: "Imagine you meet this colleague again after the project has changed. Reconnect, explain the change briefly, and invite their perspective." },
    { slug: "status-update", title: "Give a useful status update", context: "A teammate asks where your work stands while several tasks are moving at once.", focus: "Concise progress", task: "Give a brief update that separates what is complete, what is in progress, and the next expected milestone. Name a blocker only if it changes the plan.", transfer: "Deliver the update to a senior stakeholder who has only a few seconds. Lead with the status and the decision or support you need." },
    { slug: "ask-for-context", title: "Ask for missing context", context: "You have been given a task but an important requirement is unclear.", focus: "Clear clarification", task: "Explain what you understand, identify the one requirement that is unclear, and ask a focused question before starting work.", transfer: "The person is busy and gives a partial answer. Ask one respectful follow-up that confirms the requirement without reopening settled details." },
    { slug: "disagree-respectfully", title: "Disagree respectfully", context: "A colleague proposes an approach you believe will create avoidable work.", focus: "Constructive disagreement", task: "Acknowledge the aim, explain the practical concern with one reason, and offer an alternative that keeps the discussion collaborative.", transfer: "Your colleague supports the original approach. State what evidence would change your view and suggest a small way to test both options." },
    { slug: "receive-feedback", title: "Receive difficult feedback", context: "Your manager gives feedback that is useful but uncomfortable to hear.", focus: "Listening and response", task: "Show that you heard the feedback, clarify one specific example if needed, and name a realistic action you will take next.", transfer: "At a later check-in, explain what you tried, what changed, and where you would still value guidance." },
    { slug: "handoff-work", title: "Hand off work clearly", context: "You need another person to continue a task while you are away.", focus: "Actionable handoff", task: "Give the current status, the next action, the owner, and the deadline. Flag one known risk or open question so the recipient can proceed independently.", transfer: "The recipient discovers a new dependency. Explain what can continue, what must pause, and who should make the next decision." },
    { slug: "reset-expectations", title: "Reset expectations", context: "A commitment is at risk and the other person has not yet heard the update.", focus: "Early expectation setting", task: "Raise the risk early, state what has changed without making excuses, and propose a revised commitment with a clear next update.", transfer: "The other person challenges the revised date. Explain the trade-off between scope, time, and quality, then invite them to choose a priority." },
    { slug: "close-a-meeting", title: "Close a meeting with clarity", context: "A discussion is ending but the owners and next steps are still unclear.", focus: "Decisions and action", task: "Summarize the decision, assign each next action to an owner, and confirm when the group will check progress.", transfer: "One participant later disputes what was agreed. Restate the decision neutrally and invite a correction before work proceeds." },
  ],
  management: [
    { slug: "prioritize-request", title: "Prioritize a competing request", context: "Two stakeholders want urgent work, but your team can only complete one item this week.", focus: "Trade-off communication", task: "Compare the requests against shared criteria, explain the cost of delaying each, and recommend one priority with a review point.", transfer: "A new fact changes the relative impact of the requests. Revisit your recommendation and explain what changed in your reasoning." },
    { slug: "explain-delay", title: "Explain a delivery delay", context: "A dependency has moved and your original delivery date is no longer realistic.", focus: "Evidence, impact and action", task: "State the new delivery risk, distinguish the confirmed dependency from assumptions, explain the impact, and offer a recovery plan with an owner.", transfer: "The dependency slips again. Update the audience with the revised options and ask for the decision needed to protect the most important outcome." },
    { slug: "share-limited-data", title: "Share limited data responsibly", context: "Early results suggest a pattern, but the sample is too small for a firm conclusion.", focus: "Facts versus interpretation", task: "Separate the observed result from your interpretation, state the sample limitation, and recommend the next check before acting.", transfer: "A leader asks whether the early signal is enough to proceed. Give a conditional recommendation and name the evidence that would strengthen or reverse it." },
    { slug: "request-resources", title: "Request additional resources", context: "A recurring workload is above capacity and you need support to protect quality.", focus: "Business case", task: "Describe the recurring demand, show its measurable impact on quality or delivery, and make a specific, time-bound request.", transfer: "The budget owner cannot approve the full request. Offer a smaller option and explain the risk it would leave unresolved." },
    { slug: "handle-escalation", title: "Handle an escalation", context: "A customer or internal partner is unhappy and wants an immediate answer.", focus: "Composure and resolution", task: "Acknowledge the impact, establish the facts you can confirm, and give a named next action with a time for your next update.", transfer: "The first proposed fix does not work. Own the gap, explain the revised response, and set expectations without promising an outcome you cannot control." },
    { slug: "recommend-a-change", title: "Recommend a process change", context: "A repeated handoff error is costing time and the team needs a practical improvement.", focus: "Recommendation structure", task: "Describe the recurring failure, connect it to its operational cost, and recommend one small change with a clear measure of success.", transfer: "A teammate raises a valid concern about the change. Adapt the pilot so the concern is tested while the success measure stays clear." },
    { slug: "align-on-risk", title: "Align on a material risk", context: "A risk is possible but not certain, and the group needs to decide how much to mitigate.", focus: "Risk and decision", task: "State the risk and what is known, compare the cost of mitigation with the cost of inaction, and ask the group to decide on a response.", transfer: "The likelihood estimate changes but the impact does not. Reframe the options and identify the trigger that should prompt a stronger response." },
    { slug: "give-development-feedback", title: "Give development feedback", context: "A capable colleague needs one specific behavior change to become more effective.", focus: "Specific and useful feedback", task: "Describe one observable behavior, its effect on the work, and a practical alternative. Invite the colleague’s view before agreeing on a next step.", transfer: "The colleague explains a constraint you had not considered. Adjust the agreed action so it is achievable and still addresses the impact." },
  ],
  leadership: [
    { slug: "make-the-case", title: "Make the case for an idea", context: "Senior stakeholders will give your proposal only a few minutes of attention.", focus: "Persuasive clarity", task: "Lead with the decision you want, connect the idea to a strategic outcome, and support it with the strongest available evidence and one trade-off.", transfer: "A stakeholder challenges the return on investment. Respond with the assumption behind your case and a measurable pilot that can test it." },
    { slug: "answer-the-hard-question", title: "Answer the hard question", context: "Someone asks for certainty that the available evidence cannot support.", focus: "Confidence without overclaiming", task: "Answer directly, distinguish what is known from what remains uncertain, and explain what evidence or event will resolve the uncertainty.", transfer: "The audience asks you to commit before that evidence arrives. Give the most responsible decision available now and state the condition for revisiting it." },
    { slug: "lead-through-change", title: "Lead through change", context: "A change will affect routines and people need to understand both why and what happens next.", focus: "Purpose and direction", task: "Explain why the change is needed, name what will be different for people, and give the first concrete action and support available.", transfer: "A team raises a concern that the original plan missed. Acknowledge the impact, explain what can still be adjusted, and set a date for a response." },
    { slug: "facilitate-conflict", title: "Facilitate a conflict", context: "Two capable people disagree about priorities and the disagreement is slowing the team.", focus: "Common ground", task: "Surface the shared outcome, summarize each position fairly, and guide the group toward a decision rule or next test.", transfer: "The disagreement continues after the first discussion. Set a bounded follow-up with clear decision ownership and a way to surface new evidence." },
    { slug: "present-a-vision", title: "Present a practical vision", context: "Your audience needs a compelling direction connected to immediate action.", focus: "Vision to action", task: "Describe the future state in terms the audience values, explain the first step toward it, and name one early sign of progress.", transfer: "A resource constraint makes the full vision unrealistic this quarter. Preserve the outcome while proposing a credible first phase." },
    { slug: "speak-with-uncertainty", title: "Speak with uncertainty", context: "A decision is needed before all information is available.", focus: "Transparent leadership", task: "Name the decision and deadline, state the key knowns and unknowns, and explain why waiting or acting now is the more responsible choice.", transfer: "New evidence arrives after the decision. Explain whether it changes the choice, what remains valid, and how you will communicate the adjustment." },
    { slug: "influence-without-authority", title: "Influence without authority", context: "You need another team to support a change even though they do not report to you.", focus: "Stakeholder influence", task: "Connect the change to the other team’s priorities, make a specific request, and offer a reciprocal contribution or low-risk first step.", transfer: "The partner team declines because of a competing commitment. Explore timing or scope options without implying they owe you support." },
    { slug: "close-a-high-stakes-review", title: "Close a high-stakes review", context: "A review has surfaced concerns and the group needs a responsible commitment.", focus: "Alignment and accountability", task: "Summarize the material concern without minimizing it, confirm the decision, and assign an owner, checkpoint, and escalation trigger.", transfer: "The owner reports that the checkpoint is at risk. Reassess the exposure, decide whether to escalate, and make the next accountability point explicit." },
  ],
};

export const generatedScenarios = (["daily", "management", "leadership"] as const).flatMap(module => templates[module].flatMap((template, templateIndex) => levels.map(level => {
  const assignedFunctions = module === "daily" ? [] : [...functions];
  const goal = goals[(templateIndex + level.level) % goals.length];
  return {
    id: `library-${module}-${template.slug}-l${level.level}`,
    version: 1,
    module,
    functions: assignedFunctions,
    goal,
    title: template.title,
    context: template.context,
    question: `${template.task} ${level.prompt}. Keep your response grounded in what is known.`,
    independentQuestion: `${template.transfer} ${level.transfer}. Respond in your own words rather than repeating your first answer.`,
    rubricVersion: `${module}-library-${level.level}`,
    focus: template.focus,
    level: level.level,
  };
})));
