import { PrismaClient } from "@prisma/client";
import { z } from "zod";
import { buildApp } from "./app";
import { prismaStore } from "./prisma-store";
import { MemoryStore } from "./memory-store";
import { productionConfigurationErrors } from "./config";
import { createAppleNotificationVerifierFromEnv, createGooglePubSubAuthenticatorFromEnv, createStorePurchaseVerifierFromEnv } from "./store-verifier";
process.env.DATABASE_URL ??= process.env.Communicatio_Caoch_DATABASE_URL;
const env = z.object({ DATABASE_URL: z.string().url().optional(), DEV_MEMORY_STORE: z.coerce.boolean().default(false), PORT: z.coerce.number().int().min(1).max(65535).default(4000), HOST: z.string().default("127.0.0.1"), NODE_ENV: z.string().default("development"), CORS_ORIGINS: z.string().default("http://localhost:3000,http://localhost:8081"), MANAGER_EMAILS: z.string().default(""), GOOGLE_OAUTH_CLIENT_IDS: z.string().default(""), OPENAI_REALTIME_ENABLED: z.coerce.boolean().default(false), OPENAI_API_KEY: z.string().optional(), BILLING_ENABLED: z.coerce.boolean().default(false), BILLING_WEBHOOK_SECRET: z.string().optional(), GOOGLE_PUBSUB_WEBHOOK_SECRET: z.string().optional(), GOOGLE_PUBSUB_AUDIENCE: z.string().url().optional(), BILLING_PRODUCT_MAP: z.string().optional(), APPLE_PRIVATE_KEY: z.string().optional(), APPLE_KEY_ID: z.string().optional(), APPLE_ISSUER_ID: z.string().optional(), APPLE_BUNDLE_ID: z.string().optional(), APPLE_ROOT_CERT_PATHS: z.string().optional(), GOOGLE_PLAY_PACKAGE_NAME: z.string().optional(), GOOGLE_SERVICE_ACCOUNT_EMAIL: z.string().optional(), GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: z.string().optional() }).parse(process.env);
if (!env.DEV_MEMORY_STORE && !env.DATABASE_URL) throw new Error("DATABASE_URL is required unless DEV_MEMORY_STORE=true");
const appleAppIdConfigured = process.env.APPLE_ENVIRONMENT === "sandbox" || Boolean(process.env.APPLE_APPLE_ID);
const storeVerifierConfigured = Boolean(env.APPLE_PRIVATE_KEY && env.APPLE_KEY_ID && env.APPLE_ISSUER_ID && env.APPLE_BUNDLE_ID && env.APPLE_ROOT_CERT_PATHS && appleAppIdConfigured && env.GOOGLE_PLAY_PACKAGE_NAME && env.GOOGLE_SERVICE_ACCOUNT_EMAIL && env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY);
const googleClientIds = env.GOOGLE_OAUTH_CLIENT_IDS.split(",").map(clientId => clientId.trim()).filter(Boolean);
const productionErrors = productionConfigurationErrors({ nodeEnv: env.NODE_ENV, databaseUrl: env.DATABASE_URL, devMemoryStore: env.DEV_MEMORY_STORE, corsOrigins: env.CORS_ORIGINS.split(",").map(origin => origin.trim()).filter(Boolean), managerEmails: env.MANAGER_EMAILS.split(",").map(email => email.trim()).filter(Boolean), googleClientIds, realtimeEnabled: env.OPENAI_REALTIME_ENABLED, realtimeApiKey: env.OPENAI_API_KEY, billingEnabled: env.BILLING_ENABLED, billingWebhookSecret: env.BILLING_WEBHOOK_SECRET, googleNotificationAudience: env.GOOGLE_PUBSUB_AUDIENCE, billingProductMap: env.BILLING_PRODUCT_MAP, storeVerifierConfigured });
if (productionErrors.length > 0) throw new Error(`Production configuration is invalid:\n- ${productionErrors.join("\n- ")}`);
const storePurchaseVerifier = createStorePurchaseVerifierFromEnv(process.env);
const appleNotificationVerifier = createAppleNotificationVerifierFromEnv(process.env);
const googlePubSubAuthenticator = createGooglePubSubAuthenticatorFromEnv(process.env);
const database = env.DEV_MEMORY_STORE ? null : new PrismaClient();
const store = env.DEV_MEMORY_STORE ? new MemoryStore() : prismaStore(database!);
const app = await buildApp(store, { logger: true, origins: env.CORS_ORIGINS.split(",").map(origin => origin.trim()), oauth: { googleClientIds }, billing: { enabled: env.BILLING_ENABLED, webhookSecret: env.BILLING_WEBHOOK_SECRET, googleNotificationSecret: env.GOOGLE_PUBSUB_WEBHOOK_SECRET, verifyGoogleNotificationRequest: googlePubSubAuthenticator, verifyPurchase: storePurchaseVerifier, verifyAppleNotification: appleNotificationVerifier } });
for (const signal of ["SIGINT", "SIGTERM"] as const) process.once(signal, async () => { await app.close(); if (database) await database.$disconnect(); });
await app.listen({ port: env.PORT, host: env.HOST });
