import { test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { PrismaClient } from "@prisma/client";
import { prismaStore } from "../src/prisma-store";
import { buildApp } from "../src/app";
test("PostgreSQL profile persistence, concurrent timezone lock, and cascading deletion", async context => {
  assert.ok(process.env.DATABASE_URL, "Set DATABASE_URL to an isolated test database and apply migrations");
  const db = new PrismaClient(); const store = prismaStore(db); const app = await buildApp(store);
  let userId: string | undefined;
  let scenarioId: string | undefined;
  context.after(async () => { await app.close(); if (scenarioId) await db.customScenario.deleteMany({ where: { id: scenarioId } }); if (userId) await db.user.deleteMany({ where: { id: userId } }); await db.$disconnect(); });
  const email = randomUUID() + "@integration.example";
  const registration = await app.inject({ method: "POST", url: "/v1/auth/register", payload: { email, password: "integration-test-password" } });
  assert.equal(registration.statusCode, 201);
  userId = registration.json().user.id;
  const headers = { authorization: "Bearer " + registration.json().token };
  const profile = { displayName: "Test learner", function: "Engineering", jobTitle: "Engineer", careerLevel: "Experienced individual contributor", audience: "Team", goal: "Explain ideas clearly" };
  const responses = await Promise.all(["Asia/Kolkata", "UTC"].map(timezone => app.inject({ method: "PUT", url: "/v1/me/profile", headers, payload: { ...profile, timezone } })));
  assert.deepEqual(responses.map(response => response.statusCode).sort(), [200,409]);
  const secondApp = await buildApp(prismaStore(db)); context.after(() => secondApp.close());
  const me = await secondApp.inject({ url: "/v1/me", headers });
  assert.equal(me.json().profile.displayName, "Test learner");
  scenarioId = `integration-${randomUUID()}`;
  const scenario = { id: scenarioId, version: 1, module: "daily", functions: [], goal: "Explain ideas clearly", title: "Explain a change", context: "A project change needs a clear explanation.", question: "Explain the change, impact and next step.", independentQuestion: "Explain a similar change to another colleague without repeating your first answer.", rubricVersion: "integration-1", focus: "Clarity and action", level: 1 };
  const createdScenario = await secondApp.inject({ method: "POST", url: "/v1/manager/scenarios", headers: { "x-manager-key": "development-manager-key" }, payload: scenario });
  assert.equal(createdScenario.statusCode, 201);
  const initialRevisions = await secondApp.inject({ url: `/v1/manager/scenarios/${scenarioId}/revisions`, headers: { "x-manager-key": "development-manager-key" } });
  assert.equal(initialRevisions.json().revisions.length, 1);
  const published = await secondApp.inject({ method: "POST", url: `/v1/manager/scenarios/${scenarioId}/review`, headers: { "x-manager-key": "development-manager-key" }, payload: { status: "published" } });
  assert.equal(published.statusCode, 200);
  const rolledBack = await secondApp.inject({ method: "POST", url: `/v1/manager/scenarios/${scenarioId}/rollback`, headers: { "x-manager-key": "development-manager-key" }, payload: { revisionId: initialRevisions.json().revisions[0].id } });
  assert.equal(rolledBack.statusCode, 200);
  assert.equal(rolledBack.json().scenario.reviewStatus, "draft");
  const finalRevisions = await secondApp.inject({ url: `/v1/manager/scenarios/${scenarioId}/revisions`, headers: { "x-manager-key": "development-manager-key" } });
  assert.equal(finalRevisions.json().revisions.length, 3);
  await db.user.delete({ where: { id: userId } });
  assert.equal(await db.userProfile.count({ where: { userId } }), 0);
  assert.equal(await db.authSession.count({ where: { userId } }), 0);
});
